name: Booga
version: 1.0
author: Syprene (trmayhem@outlook.com)
main: io.booga.plugin.Main
softdepend: [Vault]

commands:
  rules:
    description: A list of all server rules.
    usage: /<command>
  booga:
    description: A listing of all of Booga's commands.
    usage: /<command>
    permission: booga.help
  booga help:
    description: A listing of all of Booga's commands.
    usage: /<command> help
    permission: booga.help
  booga status:
    description: Check war / grace / peace time status.
    usage: /<command> status
    permission: booga.status
  booga offer:
    description: Sacrifice diamonds to increase peace time and gain good status effects.
    usage: /<command> offer [amount]
    permission: booga.offer
  booga claim:
    description: Claim the chunk you're standing in as your own.
    usage: /<command> claim
    permission: booga.claim
  booga unclaim:
    description: Unclaim the chunk you're standing in.
    usage: /<command> unclaim
    permission: booga.claim
  booga unclaim all:
    description: Unclaim all of your owned chunks.
    usage: /<command> unclaim all
    permission: booga.claim
  booga explosives:
    description: Enabled / disable explosives in the chunk you're standing in.
    usage: /<command> explosives [on/off]
    permission: booga.toggle-explosives
permissions:
  booga.user.*:
    description: Gives access to all standard Booga commands.
    children:
      booga.help: true
      booga.claim: true
      booga.status: true
      booga.offer: true
      booga.explosives: true
      booga.config: false
  booga.help:
    description: Allows you to see list of Booga commands.
    default: true
  booga.claim:
    description: Allows you claim / unclaim chunks.
    default: true
  booga.status:
    description: Allows you to see war / grace / peace time status.
    default: true
  booga.offer:
    description: Allows you sacrifice diamonds for protection and blessings.
    default: true
  booga.explosives:
    description: Allows you to enable or disable explosives in an owned chunk.
    default: true
  booga.config:
    description: Allows you to save or reload the current Booga config.
    default: false